give @s cso:vazio
give @s cso:nucleo_sintetico
give @s cso:base_de_sintese
give @s cso:painel_de_sintese
give @s cso:mesa_de_trabalho_avancada
give @s cso:base_de_compressao
give @s cso:mecanismo_prensador
give @s cso:base_motora
give @s cso:camara_de_mistura
give @s cso:minerio_de_platina
give @s cso:minerio_de_platina_de_ardosiabissal
give @s cso:minerio_de_lazurita_de_ardosiabissal
give @s cso:minerio_de_calcopirita
give @s cso:minerio_de_grafite
give @s cso:minerio_de_lazurita
give @s cso:minerio_de_grafite_de_ardosiabissal
give @s cso:minerio_de_calcopirita_de_ardosiabissal
give @s cso:grafite_bruto
give @s cso:minerio_de_berilo_de_ardosiabissal
give @s cso:lazurita
give @s cso:minerio_de_berilo
give @s cso:platina_bruta
give @s cso:calcopirita_bruta
give @s cso:berilo
give @s cso:areia_umida
give @s cso:diamante_bruto
give @s cso:fragmento_de_diamante
give @s cso:silicio
give @s cso:quartzo_enriquecido
give @s cso:silicio_fundido
give @s cso:corante_vermelho_concentrado
give @s cso:corante_roxo_concentrado
give @s cso:ferro_refinado
give @s cso:po_de_cobre
give @s cso:corante_verde_concentrado
give @s cso:fragmento_de_obsidiana
give @s cso:po_energetico
give @s cso:liga_de_cobre_bruto
give @s cso:beriloferrita
give @s cso:calcopirita_bruta_fundida
give @s cso:platina
give @s cso:minerio_de_hematita
give @s cso:minerio_de_hematita_de_ardosiabissal
give @s cso:hematita_bruta
give @s cso:areia_ferruginosa
give @s cso:hematita
give @s cso:cascalho_enriquecido
